name = "fps"

[build]
assets = [
    "static/*/dist/index.html",
    "static/*/dist/assets/*",
    "static/simple-fps/dist/assets/89-terrain/*",
    ]

[deploy]
include = [
    "static/*/dist/index.html",
    "static/*/dist/assets/*", 
    "static/simple-fps/dist/assets/89-terrain/*",
]