name = "fps"

[build]
assets = [
    "static/*/dist/index.html",
    "static/*/dist/assets/*",
    "static/simple-fps/dist/assets/89-terrain/*",
    "static/all-about-shinji/.env.local",
    "static/prometheus-novel/dist/novel.txt",
    ]

[deploy]
include = [
    "static/*/dist/index.html",
    "static/*/dist/assets/*", 
    "static/simple-fps/dist/assets/89-terrain/*",
    "static/all-about-shinji/.env.local",
    
]